/var/log/nginx/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    rotate 30
    compress
    missingok
    notifempty
    create 0644 nginx nginx
    postrotate
        /usr/sbin/nginx -s reopen > /dev/null 2>&1
    endscript
}
